# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('developer', models.CharField(max_length=128)),
                ('platform', models.CharField(max_length=128)),
                ('releaseDate', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('views', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='game_images')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='review_images')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstName',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
