# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20170322_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
